namespace WinUI3Example
{
    [bindable]
    [default_interface]
    runtimeclass IIncrementLoadingVector : Windows.Foundation.Collections.IObservableVector<Object>
    {
        IIncrementLoadingVector();
    }
}
